//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsAppTestCRUD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacient
    {
        public string fullname { get; set; }
        public string login { get; set; }
        public string pwd { get; set; }
        public string guid { get; set; }
        public string email { get; set; }
        public int social_sec_number { get; set; }
        public string ein { get; set; }
        public string social_type { get; set; }
        public string phone { get; set; }
        public int passport_s { get; set; }
        public int passport_n { get; set; }
        public long birthdate_timestamp { get; set; }
        public int id { get; set; }
        public string country { get; set; }
        public string insurance_name { get; set; }
        public string insurance_address { get; set; }
        public int insurance_inn { get; set; }
        public string ipadress { get; set; }
        public int insurance_pc { get; set; }
        public int insurance_bik { get; set; }
        public string ua { get; set; }
    }
}
